version: '3.8'

services:
  mongodb:
    build: 
      context: ./mongodb
      dockerfile: Dockerfile
    container_name: app_monitor_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
      - MONGO_INITDB_DATABASE=app_monitor
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/app_monitor --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - app_network

  app:
    build: .
    container_name: app_monitor
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://admin:adminpassword@mongodb:27017/app_monitor?authSource=admin
      - FLASK_HOST=0.0.0.0
      - FLASK_PORT=5000
      - FLASK_ENV=development
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app_network
    restart: unless-stopped

networks:
  app_network:
    driver: bridge

volumes:
  mongodb_data:
