version: '3.8'

services:
  app:
    build: .
    container_name: app_monitor
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - MONGO_URI=mongodb://app_user:app_password@mongodb:27017/app_monitor?authSource=app_monitor
    volumes:
      - .:/app
    depends_on:
      - mongodb
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=app_monitor
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
      - MONGO_INITDB_USERNAME=app_user
      - MONGO_INITDB_PASSWORD=app_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network
    restart: unless-stopped
    command: ["mongod", "--auth"]

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
